### ISSUE TITLE
Installation Instructions Missing

### ISSUE THREAD

**Issue by GadgetSteve** [jeffbarish/wax#2]
The manual does not seem to include any installation instructions nor are there releases present in this GitHub repo.

**Comment by jeffbarish** [comment]
True. The installation instructions are in the README for wax-install, but I like the idea of sticking them in the manual also. 

I could not figure out the point of releases. Is it the case for some repositories that the code could be in an un-runnable state if it is not marked as a release? Currently that is not the case for wax, but since you asked I suppose that I should mark something as a release.

By the way, the manual that appears at readthedocs is inconsistent with the rst files. I cannot figure out how to get readthedocs to update.

I have never used github before, so I appreciate your suggestions.

**Comment by GadgetSteve** [comment]
I'll try to get back to you on both in the next few days.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jeffbarish** [comment]
I got the manual to update and I added a chapter for installation and quick start. I also created an initial release for wax.

**Comment by GadgetSteve** [comment]
Snowed under with work I am afraid - good to hear. I will close this issue.
